version: '2.0'

services:
  mysql-docker-contain:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Tech
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - /data/mysql
  spring-boot-jpass:
    image: divyanshitech3
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-contain
    ports:
      - 10001:10001
    volumes:
      - /data/spring-boot-jpass
    command: java -jar /usr/app1/TechPublishing-0.0.1-SNAPSHOT.jar
